import React from 'react';
import { useNavigate } from 'react-router';
import '../style/landing.scss';

const Landing = () => {
  const navigate = useNavigate();

  return (
    <div className="landing-page">
      {/* Navigation */}
      <nav className="landing-nav">
        <div className="landing-nav__logo">
          <img src="/logo.png" alt="PrepAI Logo" className="logo-img" />
          <span className="logo-text">PrepAI</span>
        </div>
        <div className="landing-nav__links">
          <button onClick={() => navigate('/login')} className="nav-btn nav-btn--ghost">Login</button>
          <button onClick={() => navigate('/register')} className="nav-btn nav-btn--primary">Get Started</button>
        </div>
      </nav>

      {/* Hero Section */}
      <header className="hero-section">
        <div className="hero-content">
          <div className="hero-badge">✨ The Future of Interview Prep</div>
          <h1 className="hero-title">
            Land Your Dream Job with <br />
            <span className="highlight">AI-Powered Strategy</span>
          </h1>
          <p className="hero-subtitle">
            PrepAI analyzes the job description and your unique profile to build a winning, 
            personalized interview roadmap in seconds.
          </p>
          <div className="hero-actions">
            <button onClick={() => navigate('/register')} className="button primary-button hero-btn">
              Start Preparing Now
            </button>
            <button onClick={() => navigate('/login')} className="button secondary-button hero-btn">
              View Dashboard
            </button>
          </div>
        </div>
        
        {/* Decorative Elements */}
        <div className="hero-glow hero-glow--blue"></div>
        <div className="hero-glow hero-glow--purple"></div>
      </header>

      {/* Features Section */}
      <section className="features-section">
        <h2 className="section-title">Why choose PrepAI?</h2>
        <div className="features-grid">
          <div className="feature-card">
            <div className="feature-icon feature-icon--blue">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 2v20M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"/></svg>
            </div>
            <h3>Custom Roadmaps</h3>
            <p>Get day-by-day preparation plans tailored exactly to the target job description and your current skills.</p>
          </div>
          
          <div className="feature-card">
            <div className="feature-icon feature-icon--indigo">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/><polyline points="10 9 9 9 8 9"/></svg>
            </div>
            <h3>Targeted Questions</h3>
            <p>Practice with high-probability technical and behavioral questions generated by our advanced AI models.</p>
          </div>

          <div className="feature-card">
            <div className="feature-icon feature-icon--purple">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><path d="M12 8v4l3 3"/></svg>
            </div>
            <h3>Save Time</h3>
            <p>Skip the endless googling. PrepAI gives you everything you need to know in one focused dashboard.</p>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="landing-footer">
        <div className="footer-content">
          <div className="footer-logo">
            <img src="/logo.png" alt="PrepAI" className="logo-img-small" />
            <span>PrepAI</span>
          </div>
          <div className="footer-links">
            <a href="#">Privacy Policy</a>
            <a href="#">Terms of Service</a>
            <a href="#">Contact Us</a>
          </div>
        </div>
        <p className="footer-copyright">© {new Date().getFullYear()} PrepAI. All rights reserved.</p>
      </footer>
    </div>
  );
};

export default Landing;
